// <auto-generated />
namespace OpenQbit.Masterdb.DataAccsess.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201706091039302_DbInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
